---
title: ""
author: ""
 

header-includes:
    \usepackage[italian]{babel}


output:
  pdf_document:
    toc: true
    number_sections: true
 
---
\listoffigures
\listoftables
# ELENCO DEI COLLABORATORI {-}
* **Dr. Tranquillo Vito** U.O. 1-Responsabile scientifico del progetto.Coordinamento delle U.O., Analisi statistica dei dati fenotipici. 
* **Dr. Fiocchi Alfredo** U.O. 1-Analisi microbiologiche e antibiogrammi.
* **Dr. Pongolini Stefano** U.O. 2-Coordinamento U.O. e attività di analisi metagenomiche
* **Dr. Bolzoni Luca** U.O. 2-Attività analisi metagenomiche e analisi dati
* **Dr. Erika       ** U.O. 2-Attività analisi metagenomiche e analisi dati
* **Dr. Bertoletti Irene** U.O. 3-Analisi Microbiologiche e antibiogrammi
* **Dr. Alessandro Bianchi** U.O. 3-Analisi Microbiologiche e antibiogrammi
* **Dr. Loris Alborali** U.O. 4-Analsi genomiche ceppi Ceftiofur resistenti
* **Dr. Prati Paola** U.O. 5- Attività di raccolta e invio campioni a U.O.1 per successive analisi
* **Dr. Gianni Sala** U.O. 6- Attività di raccolta e invio campioni a U.O.1 per successive analisi

# RELAZIONE FINALE VERSIONE INTEGRALE {-}

# INTRODUZIONE (max 5 pagine)
L'Antibiotico-Resistenza (AR) è una grave minaccia per la salute umana, in quanto compromette la capacità di trattare le infezioni. La resistenza agli antibiotici si sviluppa attraverso complessi meccanismi come la mutazione sotto la pressione selettiva derivante dall'uso/abuso di antibiotici in medicina umana e veterinaria, o frequentemente da acquisizione di geni che si sono evoluti nel corso del tempo nei batteri nell'ambiente. Il serbatoio di geni di resistenza nell'ambiente è un mix
di resistenza naturale e quella presente nelle deiezioni di animali e uomini, a cui si possono aggiungere gli effetti selettivi di inquinanti, che possono co-selezionare elementi genetici mobili che trasportano più geni di resistenza.L'interesse per il ruolo della fauna selvatica nella diffusione e nel mantenimento dell'antibiotico-resistenza è aumentato nel corso degli ultimi 10 anni, con un costante aumento della produzione scientifica.La principale preoccupazione nasce dall'ipotesi, in corso di verifica, che l'eventuale dimostrazione che la fauna selvatica funga da "serbatoio" di batteri protatori di geni di resistenza e contribuisca alla contaminazione ambientale di batteri resistenti o materiale genetico
di resistenza (resistoma), possa compromettere gli sforzi messi in atto, soprattutto in questi ultimi anni, in campo medico e veterinario per ridurre la diffusione del fenomeno della resistenza agli antibiotici. 
La presenza nella fauna selvatica, normalmente non sottoposta a trattamenti antibiotici, di ceppi batterici resistenti e in generale di geni di resistenza, è opinione comune sia da attribuire a fenomeni di contaminazione ambientale , oltre a noti fenomeni di resistenza naturale di ceppi batterici come strumento di difesa nei confronti di antibatterici prodotti da diversi generi di microrganismi come funghi, lieviti, ecc. Per definire il ruolo della fauna selvatica nel complesso meccanismo di diffusione e mantenimento dell'antibiotico resistenza è necessario acquisire informazioni relativamente alla prevalenza di animali selvatici portatori di ceppi batterici resistenti nelle differenti specie e come questa varia in base all'etologia ed ecologia delle specie ospite. La caratterizzazione fenotipica e genotipica dei batteri isolati da specie selvatica e la prevalenza di ceppi resistenti e multiresistenti. La necessità di colmare le evidenze scientifiche di questo tipo ha portato ad un incremento di studi sull'argomento, comportando nell'arco di una decina d'anni l'accumulo di evidenze che aiutano a definire meglio il ruolo della fauna selvatica nella diffusione e nel mantenimento dell'antibiotico-resistenza.
Una “scoping review”(cit[xxxx]) pubblicata nel 2015, ha evidenziato la presenza di 866 articoli di ricerca primaria; Oltre il 90% erano studi osservazionali; la maggioranza riportano i dati di prevalenza per AR nella fauna selvatica (551/866, 63.6%). Ci sono stati 176 di 866 (20,3%) studi  di genotipizzazione.   AR è stata più frequentemente studiata in E. coli 150 di 866 (17,3%), Salmonella 83 di 866 (9,6%) e Enterococcus 48 di 866 (5,5%). I gruppi della fauna selvatica più frequentemente studiati erano uccelli 410 su 866 (47,3%), cervidi, 133 di 866 (15,4%) e roditori 91 di 866 (10,5%). Solo 11 articoli hanno studiato la contaminazione dei prodotti, e ci sono stati 26 casi di vettori intermedi, come le mosche o insetti. La contaminazione ambientale è stata più frequentemente riportati per l'acqua 130 di 866 (15%). Le modalità di trasmissione dell’AR è stata riportata in 110 articoli (12,7%). Tra le caratteristiche ambientali che sono state segnalate come fattori di rischio per il trasferimento di batteri patogeni e /o AR vi sono: condivisione di ambienti  161 di 866 (18,6%), infestazione o mancanza di controllo degli uccelli selvatici 124 di 866 (14,3%) e delle fonti idriche condivise 98 di 866 (11,3%). Le pratiche di mitigazione, strategie o programmi per ridurre la trasmissione di batteri e / o AR sono stati discussi o studiati in 124 su 866 (14,3%) articoli. Sono state fornite informazioni circa i tassi di contatto tra fauna selvatica e animali domestici in 29 articoli (3,3%). È interessante notare che numerosi articoli di ricerca primaria (122/866, 14.1%) hanno riportato associazioni statisticamente significative per i fattori di rischio di trasmissione di AR o batteri patogeni dalla fauna selvatica agli animali cibo, fonti ambientali o umani. Uno dei primi lavori in Italia sull’AR nella  fauna selvatica è stato condotto da Caprioli et al:(cit) sono stati  raccolti 81 campioni di feci da mammiferi selvatici (ruminanti, Marmotta) che vivono in Parco Nazionale dello Stelvio. Lo studio è stato focalizzato solo su Escherichia coli come microrganismo target. Sono stati osservati ceppi AR di E.coli in 17 dei 121 ceppi  presi in esame. ARB isolati hanno mostrato un profilo di multiresistenza. Gli autori hanno concluso che i ceppi di E. coli in animali selvatici possono essere resistenti a diversi agenti antimicrobici e portatori di  plasmidi R, anche se il microbioma intestinale degli animali selvatici non è direttamente esposta agli antibiotici. Così una possibile fonte di AR in E.coli potrebbe essere quegli esseri umani e animali domestici che portano AMRB e condividono gli stessi habitat (turisti, animali domestici pascolo) di animali della fauna selvatica. In IZSLER l’attività di routine nel periodo tra il 2002 e il 2016 mostra che sono stati eseguiti 404 antibiogrammi di ceppi di batteri isolati da animali selvatici. Tutti questi ceppi mostrano resistenza ad almeno un antibiotico. Nel 96% si è osservata multi-resistenza; 77% erano ceppi di Salmonella spp isolati da oltre 300 cinghiali. E. coli è stato il secondo ceppo più analizzato (51). Tra le altre specie di fauna selvatica indagati sono: 27 ruminanti, 22 uccelli, 42 lepri, 2 volpi e un riccio. Questi dati sono indicativi della presenza e della circolazione di ARB e ARG nella fauna selvatica delle Alpi.








# MATERIALE E METODI (max 10 pagine)

## Campionamento

## Esami microbiologici

## Antibiogrammi

## Analisi metagenomiche

## Analisi dei dati

# RISULTATI

## QUADRO GENERALE

### Territorio

### Fauna selvatica

### Esami microbiologici

### Antibiogrammi

## PREVALENZA DI CEPPI ANTIBIOTICO-RESISTENTI E MULTI-RESISTENTI NELLA FAUNA SELVATICA

## CARATTERIZZAZIONE FENOTIPICA DELL'ANTIBIOTICO-RESISTENZA DEGLI ISOLATI BATTERICI

## POOL METAGENOMICI

# DISCUSSIONE E CONCLUSIONI (max 10 pagine)

# BIBLIOGRAFIA

# Raccomandazioni (max 2 pagine)
### elementi gestionali e/o diagnostici
### indicazioni per la ricerca
### sugg per eventuali provvedimenti normativi

# MODALITÀ DI DIVULGAZIONE DEI RISULTATI (1 pagina)


