---
title: ''
author: ''
header-includes: \usepackage[italian]{babel} \usepackage{setspace}\doublespacing \usepackage{float} 
                  \usepackage{booktabs} \usepackage{longtable} 
output:
  pdf_document:
    toc: yes
    number_sections: yes
    fig_caption: yes
  html_document:
    toc: yes
    df_print: paged
  word_document:
    toc: yes
bibliography: amrRef.bib
link-citations: yes
linkcolor: blue
---

\listoffigures
\listoftables

### ELENCO DEI COLLABORATORI {-}

* **Dr. Tranquillo Vito** U.O. 1-Responsabile scientifico del progetto.Coordinamento delle U.O., Analisi statistica dei dati fenotipici. 
* **Dr. Fiocchi Alfredo** U.O. 1-Analisi microbiologiche e antibiogrammi.
* **Dr. Pongolini Stefano** U.O. 2-Coordinamento U.O. e attività di analisi metagenomiche
* **Dr. Bolzoni Luca** U.O. 2-Attività analisi metagenomiche 
* **Dr. Erika Scaltriti** U.O. 2-Attività analisi metagenomiche 
* **Dr. Bertoletti Irene** U.O. 3-Analisi Microbiologiche e antibiogrammi
* **Dr. Alessandro Bianchi** U.O. 3-Analisi Microbiologiche e antibiogrammi
* **Dr. Loris Alborali** U.O. 4-Analsi genomiche ceppi Ceftiofur resistenti
* **Dr. Prati Paola** U.O. 5- Attività di raccolta e invio campioni a U.O.1 per successive analisi
* **Dr. Gianni Sala** U.O. 6- Attività di raccolta e invio campioni a U.O.1 per successive analisi
