library("readxl")
library("tidyverse")
library("DataExplorer")
library("janitor")
library("hrbrthemes")
library("leaflet")
library("maps")
library("rgdal")
library("sp")
library("lubridate")
library("rmapshaper")
library("patchwork")
library("mapview")
library("ggridges")
library("knitr") 
library("kableExtra")
library("gridExtra")
library("htmlwidgets")
library("htmltools")
library("binom")
# library(FactoMineR)
# library(factoextra)
library("rstanarm")
library("emmeans")
library("tidybayes")
library("vegan")
library("BiodiversityR")
library("sjPlot")
library("fastDummies")
#library(iNEXT)
library("GGally")
library("rethinking")
#library(plyr)
library("RColorBrewer")


